const ACTIONS = {
  ADD: "ADD",
  APPEND: "APPEND",
  DELETE: "DELETE",
  EDIT: "EDIT",
  ERROR: "ERROR",
  GET: "GET",
  RESET: "RESET",
  RETRIEVE: "RETRIEVE",
  SET: "SET",
  UPDATE: "UPDATE",
};
export default ACTIONS;
